project:
  type: website

website:
  title: "Eric Abelson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: experience.qmd
        text: Experience

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

