---
title: "Resume"
format:
  html:
    grid:
      sidebar-width: 300px
      margin-width: 250px
      gutter-width: 1.5rem
---

## Skills

Decisions from data; experimental & study design; GenAI (e.g., dual-prompting, multi-step reasoning, contextual understanding, intent recognition); statistical analysis & ML (e.g., hypothesis testing, causal inference, regression/time-series/hierarchical clustering); ETL; hyperparameter tuning; program R; high-dimensional data collection, cleaning, analysis, visualization, and interpretation; spatial analysis; commitment to diversity, equity, and inclusivity; communication; collaboration; public speaking; teaching; mentorship; writing; budget management

## Education

+:----------+:---------------------------------------------------------------------------+--------:+
| **Ph.D.** | **Stanford University\                                                     | 2013    |
|           | **Department of Biological Sciences, Palo Alto, CA                         |         |
+-----------+----------------------------------------------------------------------------+---------+
| **M.S.**  | **Stanford University**\                                                   | 2008    |
|           | Department of Biological Sciences, Palo Alto, CA\                          |         |
|           | GPA: 4.0/4.0                                                               |         |
+-----------+----------------------------------------------------------------------------+---------+
| **B.S.**  | **University of California, Berkeley\                                      | 2005    |
|           | **Department of Environmental Science Policy and Management, Berkeley, CA\ |         |
|           | Minor in Forestry and Natural Resources\                                   |         |
|           | GPA: 3.9/4.0                                                               |         |
+-----------+----------------------------------------------------------------------------+---------+
| **A.S.**  | **Cabrillo College**, Santa Cruz\                                          | 2003    |
|           | Associate in Science with Honors\                                          |         |
|           | GPA:4.0/4.0                                                                |         |
+-----------+----------------------------------------------------------------------------+---------+
| **A.A.**  | **Cabrillo College**, Santa Cruz\                                          | 2003    |
|           | Associate in Arts with Honors\                                             |         |
|           | GPA: 4.0/4.0                                                               |         |
+-----------+----------------------------------------------------------------------------+---------+

## Experience Highlights

-   Participation in Diversity, Equity, and Inclusion programs
-   Planning, conducting, and directing research (study design to reporting) to provide actionable insights based on novel data
-   Large-scale and high-complexity data collection & analysis including: data wrangling, cleaning, reshaping, dimension-reduction, analytics, mining, visualization, and archiving
-   Program R
-   Use of advanced quantitative statistical and machine learning methods and spatial analytical techniques
-   Use of high-performance computing clusters to conduct analyses
-   Biological applications of computer science and collaborations with computer scientists
-   Develop project proposals, obtain competitive funding, coordination with personnel and stakeholders, deploying field infrastructure
-   Forming and working with partnerships of stakeholders (government, non-profit, general public, academia).
-   Written and verbal reporting to communicate complex analyses in straightforward and practical language
-   Spatial analyses, biogeography, landscape analyses, remote detection/tracking of wildlife
-   Balanced multiple responsibilities including allocating resources, budgeting, and identifying workforce and organizational needs to establish and meet objectives. Experience includes recruiting, hiring, and managing employees.

## Professional Experience

+:---------------------------------------------------------------+:------------------------------------+------------------------:+
| **Method Qualitative**                                         | Chief Science Officer               | 2023-Present            |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **University of Texas, Austin**                                | Research Scientist                  | 2020-2025               |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **USDA Pacific Southwest Research Station**                    | Postdoctoral Scholar                | 2015-2020               |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **University of California, Los Angeles**                      | La Kretz Conservation\              | 2014-2015               |
|                                                                | Postdoctoral Fellow                 |                         |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **University of California, Davis\                             | Visiting Scholar                    | 2015-2018               |
| (John Muir Inst. of the Environment)**                         |                                     |                         |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **U.C. Los Angeles**                                           | Visiting Scholar                    | 2015-2018               |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **Jasper Ridge Biological Preserve, \                          | Instructor/Researcher               | 2013-2018               |
| Stanford University**                                          |                                     |                         |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **JDR Environmental, Martinez, CA**                            | Research Biologist                  | 2013-2014               |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **San Francisco Public Utility Commission, San Francisco, CA** | Biological Research Graduate Intern | 2013                    |
+----------------------------------------------------------------+-------------------------------------+-------------------------+
| **Segue Music, West Hollywood, CA**                            | Computer Consultant,\               | 1998-2001               |
|                                                                | Audio Engineer                      |                         |
+----------------------------------------------------------------+-------------------------------------+-------------------------+

## Publications and Patents

`*` indicates undergraduate co-author/advisee, `^` indicates corresponding author

Russo, N., K. Gahm, M. Zuercher, K. Hernandez, R. Blakey, C. Niesner, **E.S. Abelson**. Monitoring animal movement diversity as a component of biodiversity. Frontiers in Ecology and the Environment. In review

Contina, A., **E.S. Abelson**, B. Allison, B. Stokes, K.F. Sanchez, H.M. Hernandez, A.M. Kepple, Q. Tran, I. Kazen, K.A. Brown, H.J. Powell, T.H. Keitt. BioSense, An Automated sensing node for organismal and environmental biology. HardwareX. (2024)

Barrientos, R., W. Vickers, T. Longcore, **E.S. Abelson**, J. Dellinger, D.P. Waetjen, G. Fandos, F.M. Shilling. Nearby night lighting, rather than sky glow, is associated with habitat selection by a top predator in human-dominated landscapes. Philosophical Transations of the Royal Society B. (2023)

\^**Abelson, E.S.**, B. Seymoure, E.K. Perkin, A. Jechow, H. Moon, C.C.M. Kyba, F. Holker, J. White, T. Longcore. Ecological Aspects and Measurement of artificial light at night. Ecology Letters. In revision. Preprint available on SSRN: <https://dx.doi.org/10.2139/ssrn.4353905>

\*Valler, J., S. Riley, D.T. Blumstein, \^**E.S. Abelson**. Impact of extreme heat events on puma movement near the urban-wildland interface. Western wildlife. In prep.

\^**Abelson, E.S.** White-flash film camera traps affect behavior and bias data collected for deer, Odocoileus hemionus. Western Wildlife. In submission

\*Nojoumi, M., A.P. Clevenger, D.T. Blumstein, \^**E.S. Abelson**. Vehicular Traffic Effects on Elk and White-tailed Deer at Wildlife Crossings in Banff National Park. Plos ONE. 17(11): e0269587. (<https://doi.org/10.1371/journal.pone.0269587>) (2022)

\^**Abelson, E.S.**, K.M. Reynolds, A.M. White, J.W. Long, C. Maxwell, P.N. Manley. Evaluating pathways to social and ecological landscape resilience. Ecology and Society. 27(4):8. (<https://doi.org/10.5751/ES-13243-270408>) (2022)

White, A.M., T.G. Holland, **E.S. Abelson**, A. Kretchun, C.J. Maxwell, R.M. Scheller. Simulating wildlife habitat dynamics to inform best management strategies under a changing climate in the Lake Tahoe basin, California. Ecology and Society. 27. (doi:10.5751/ES-13301-270231) (2022)

\^**Abelson, E.S.**, J. Sikich, S. Riley, D.T. Blumstein. Influence of anthropogenic light on puma road crossing movement. bioRxiv: doi: <https://doi.org/10.1101/2022.10.28.514303> (2022)

Keitt T., **E.S. Abelson**. Ecology in the age of automation. Science 373:6557, 858-859 (2021)

Niesner, C.A., R.V. Blakey, D.T. Blumstein, \^**E.S. Abelson**. Wildlife affordances of urban infrastructure: a framework to understand human-wildlife space use. Frontiers in Conservation Science. 2:774137 (2021)

\^**Abelson, E.S.**, K.M. Reynolds, P. N. Manley, S. Paplanus. Strategic decision support for long-term conservation management planning. Forest Ecology and Management. 497 (2021)

Miller, A.B., D. King, M. Rowland, J. Chapman, M. Tomosy, C. Liang, **E.S. Abelson**, R. Truex. Sustaining wildlife with recreation on public lands: a synthesis of research findings, management practices, and research needs. Gen. Tech. Rep. PNW-GTR-993. Portland, OR: US Department of Agriculture, Forest Service, Pacific Northwest Research Station. 226 p. 993 (2020).

\^**Abelson, E.S.** Big brains reduce extinction risk in Carnivora. Oecologia (2019)

\*Neco, L.C., **E.S. Abelson**, B. Natterson-Horowitz, D.T. Blumstein. The evolution of self-medication behaviour in mammals. Biol J Linn Soc 128, 373-378 (2019)

Boyston, E.E., **E.S. Abelson**, \*A. Kazanjian, D.T. Blumstein. Canid vs. canid: insights into coyote-dog encounters from social media. Human Wildlife Interactions. (2018) 12(2), 9

\^**Abelson, E.S.** Brain size is correlated with endangerment status in mammals. Proc. R. Soc. B. Vol. 283. No. 1825. The Royal Society, 2016.

Garcia-Molina, H., \*S. Kandel, A. Paepcke, M. Theobald, and **E.S. Abelson**. ‘Spreadsheet system and method for managing photos,’ Patent publication number: US 2010/0058163 A1 U.S. Classification: 715/220

Sundaresan, S., C. Riginos, **E.S. Abelson**. Storage and analysis of camera trap data: alternative approaches (Response to Harris et al. 2010). The Bulletin of the Ecological Society of America 92.2 (2011): 188-195.

Kandel, S., **E.S. Abelson**, H. Garcia-Molina, A. Paepcke & M. Theobald. 2008. PhotoSpread: a spreadsheet for managing photos. Computer/Human Interactions, 2008 Proceedings 1749-1758. Available online at: <http://dbpubs.stanford.edu:8090/pub/2007-28>

## Mentorship

-   Graduate student committee member: Academic barriers for disabled students in STEM
-   Graduate student committee member: Wildlife movement
-   Mentorship: Mentored 42 Stanford, U.C. Berkeley and U.C. Los Angeles, San Francisco, University, U.C. Davis, and U.T. Austin undergraduates, masters, and Ph.D. students; two high school students; and seven local volunteer/recent university graduates in research design, field work, database management and analysis. 2006-Present
-   Ph.D. student Mentor: Stanford Biosciences Student Association Mentorship program provides mentoring for 1st year Ph.D. students. Stanford University, CA. October 2011-2013
-   ESA SEEDS Mentor: Ecological Society of America program entitled, Strategies for Ecology Education, Diversity and Sustainability, is a mentorship program that pairs ecologists with under-represented students. Portland, OR. 2012 ESA Annual Meeting

## Presentations

### Invited Seminars

Wildlife Corridor Webinar, Environment California.Wildlife Corridors and Connectivity.September 2021.Los Angeles, CA.

La Kretz Center for California Conservation Science 2021 Public Lecture. May 2021.Los Angeles, CA.

Abelson, E.S. Lake Tahoe West - synthesis of biophysical, ecological, economic, and social data.Lake Tahoe West symposium.May 2020.Lake Tahoe, CA.

Wildlife movement ecology, applications for conservation planning. The Nature Conservancy – Connected Lands Strategy Team (Land Networks Program). December 2018, San Diego, CA.

Modeling wildlife movement for conservation planning. USFS Pacific Southwest Research Station, Conservation Biology. March 12, 2018, Davis, CA.

Modeling wildlife movement for conservation planning. California Department of Transportation – Environmental Planning Division. November 21, 2017, Marysville, CA.

Brain size as a predictor for extinction risk in mammals. U.C. Davis Animal Behavior Seminar Series, September 2017, Davis, CA.

Connectivity modeling. The Center for Large Landscape Conservation, March 2017, Bozeman, MT.

Connectivity modeling: modeling wildlife corridors. Innovative Approaches to Wildlife and Highway Interactions: Advanced Course in Transportation Ecology, July 28, 2016. Sagehen Creek Field Station, CA

Artificial light at night: impacts to mammals. International Dark-sky Association, November 2015. Phoenix, AZ

Wildlife movement and behavior at the roadside. La Kretz League, November 2014. La Kretz Field Station. Malibu, CA.

Wildlife movement and behavior at the roadside. Santa Monica Mountains Science Day, September 2014. Santa Monica Mountains National Park Service Headquarters. Thousand Oaks, CA

Integrating wildlife behavior and conservation in a changing world. Environmental Constraints on Cognition Seminar Series, February 2014. UC Berkeley. Berkeley, CA

Integrating wildlife behavior and conservation in a changing world. UCLA La Kretz Postdoctoral Fellow Seminar, October 2013. U.C.L.A. Los Angeles, CA

### Research Presentations

`*` indicates undergraduate co-author/advisee

Barrientos, R., T. Longcore, **E.S. Abelson**, J. Dellinger, D. Waetjen, B. Markman, F. Shilling. Human footprint and mountain lion territory use in human-dominated landscapes. Infrastructure & Ecology Network, September 22, 2022, Cluj-Napoca, Romania.

Saurabh, S., C. King, M. Marder, L. Lake, **E.S. Abelson**. An agent-based approach to studying energy and economic coupling in a limited-resourced society. University of Texas Energy Symposium, September 6, 2022, Austin, TX

\*Gladden, N., S. Jha, **E.S. Abelson**, Griffin, S. Pollinator foraging is impacted by plant characteristics, environmental factors, and air pollution. Summer Research Symposium, July 28, 2022, Austin, TX. (poster presentation)

Saurabh, S., C.W. King, L. Lake, M. Marder, **E.S. Abelson**, L. Merceron. An agent-based approach to consumption, inequality in distribution and sustainability of a limited sourced energy-dependent society. Stanford Macro-Energy Systems Workshop, July 2022, Stanford, CA. (poster presentation)

Jacobson S., S. Crossen, **E.S. Abelson**. Carcass data: when fewer is not better. International Conference on Ecology & Transportation, September 24, 2019, Sacramento, CA. (poster presentation)

**Abelson, E.S.**, S.A. Cushman. Modeling wildlife movement behavior to identify mitigation locations along linear barriers. The Western Section of the Wildlife Society Annual Meeting. February 6, 2019. Fish Camp, California.

**Abelson, E.S.**, S. Cushman. Wildlife movement models for conservation planning along linear barriers. The Wildlife Society Annual Meeting, October 2018, Cleveland, OH.

**Abelson, E.S.**, S. Cushman. Conservation modeling to identify optimal barrier crossing-locations. Society for Conservation Biology: North American Congress for Conservation Biology, July 2018, Toronto, Ontario, CA.

**Abelson, E.S.** Applying wildlife movement modeling and behavior to inform highway mitigation activities. Bay-Area Conservation Biology Symposium, May 2018, Davis, CA.

Roe J.D., T. McCleary, **E.S. Abelson**. Efficacy of camera traps to detect herpetofauna with emphasis on the Alameda Whipsnake and San Francisco Garter Snake. The Wildlife Society Annual Meeting, September 2017, Albuquerque, NM

**Abelson E.S.**, S. Cushman. Modeling wildlife movement for conservation planning. Ecological Society of America Annual Meeting, August 2017, Portland, OR

**Abelson, E.S.**, S. Jacobson. The importance of within-species wildlife behavior on mitigating mortalities and the barrier-effect of highways. International Conference on Ecology and Transportation, May 2017, Salt Lake City, UT

**Abelson, E.S.**, S. Jacobson. Moving wildlife across roads with PSW Research Station. Women and Minorities in U.S.F.S. Research Workshop, October 2016, Portland, OR. (poster presentation)

**Jacobson, S.**, C. de Rivera, E.S. Abelson. Impacts of roadways on wildlife: barrier impacts from vehicle-caused mortality and road avoidance on species and populations. Society for Conservation Biology: North American Congress for Conservation Biology, July 2016, Madison, WI

\*Nojoumi, M., **E.S. Abelson**, A.P. Clevenger, D.T. Blumstein. Vehicular traffic effects on elk and white-tailed deer at wildlife crossings in Banff National Park. UCLA Ecology and Evolutionary Biology Poster Day, May 2016, Los Angeles, CA (poster presentation. Awarded second place in poster competition)

\* Nojoumi, M., **E.S. Abelson**, A.P. Clevenger, D.T. Blumstein. Vehicular traffic effects on elk and white-tailed deer at wildlife crossings in Banff National Park. UCLA Science Poster Day, May 24 2016, Los Angeles, CA (poster presentation)

**Abelson, E.S.**, S.P.D. Riley, D.T. Blumstein. Wildlife movement, road ecology and impacts of wildlife perception. Organized session: “Road ecology – moving forward.” Ecological Society of America Annual Meeting, August 2015, Baltimore, MD

\*Kazanjian, A., **E.S. Abelson**, E.E. Boydston, D.T. Blumstein. Canid vs. canid: Using social media to understand coyote-dog encounters. UCLA Ecology and Evolutionary Biology Poster Day, May 2014, Los Angeles, CA (poster presentation)

\*Kazanjian, A., **E.S. Abelson**, E.E. Boydston, D.T. Blumstein. Canid vs. canid: Using social media to understand coyote-dog encounters. UCLA Science Poster Day, May 2014, Los Angeles, CA (poster presentation)

\*Zuckerwise, A., **E.S. Abelson**, R. Dirzo. Temporal overlap among wildlife species at Jasper Ridge Biological Preserve. Symposium of Undergraduate Research and Public Service, April 25 2015, Stanford, CA

\*Neco, L.C., **E.S. Abelson**, A. Brown, B. Natterson-Horowitz, D.T. Blumstein. The Evolution of Self-Medication Behavior in Mammals. XXXII Encontro Anual de Etologia e V Simpósio Latino-americano de Etologia, November 18-21, 2014. Rio Grande do Norte, Brasil.

**Abelson, E.S.** Relative brain size as a predictor for mammalian extinction vulnerability. Ecological Society of America Annual Meeting, August 2012, Portland, OR

**Abelson, E.S.** Can brain size help predict conservation status of mammalian species? Society for Conservation Biology: North American Congress for Conservation Biology, July 2012, Oakland, CA

**Abelson, E.S.** Endocranial capacity as a predictor for extinction risk in mammals. The CHI Conference, September 14, 2011, Stanford, CA

**Abelson, E.S.** Are wildlife camera-shy? Capture bias and behavioral response to TrailMaster 1550 camera traps. The Wildlife Society Annual Conference, September 20, 2009, Monterey, CA

**Abelson, E.S.** Camera-shy wildlife and capture bias: behavioral response to TrailMaster 1550 camera traps. Ecological Society of America Annual Meeting, August 6, 2009, Albuquerque, NM

**Abelson, E.S.** Behavioral Response to the TrailMaster 1550 via a Comparative Study of Two Detection Methods. Bay Area Conservation Biology Symposium, January 31, 2009, Stanford, CA.

**Kandel, S., E.S.** Abelson, H. Garcia-Molina, A Paepcke & M. Theobald. PhotoSpread: a spreadsheet for managing photos. Conference on Human Factors in Computing Systems, April 8, 2008, Florence, Italy.

**Abelson, E.S.** Behavioral Biases of Traditional Camera Trapping Methodologies. Jasper Ridge Biological Preserve, April 08, 2007, Portola Valley, CA.

**Abelson, E.S.** Tracking as a wildlife survey technique. College of Natural Resources Honors Research Symposium, May 11, 2005, Berkeley, CA.

`*` indicates undergraduate mentee & co-author

## Scientific Outreach & Professional Service

-   Service: U.T. Austin College of Natural Sciences; Diversity, Equity, and Inclusion committee member 2021-present
-   Service: Illuminating Engineering Society; Outdoor Nighttime Environments taskforce member 2022-present
-   Peer reviewer: Peer reviewer for Biological Conservation, PLOS ONE, Proceedings of the Royal Society B, Biological Sciences, Journal of Mammalogy
-   Invited Workshop participant: Wildlife crossings experts meeting. Workshop on enhancing habitat connectivity for wildlife in the Santa Ana to Palomar Mountains region, California. February 2022.
-   Committee board member: Board member for the Animal Behavior Society’s Conservation Committee. 2014-2017.
-   Board of Directors: Amigos del Centro de Educacion Ambiental de las Peninsula Yucateca. Member of the board of directors for the 501 c3 non-profit organization based in Mexico with the mission of conserving and supporting of bio-cultural diversity through education, research and community. November 2012-2021.
-   Workshop participant: Effective Collaboration & Diversity in Scientific Teams. Workshop on cultural/gender diversity in the sciences and collaborations within and across disciplines. February 2015.
-   Workshop participant: Southern California Puma Project and National Park service three day workshop to identify optimal crossing locations. January 2015.
-   Committee member: Committee member for the UCLA La Kretz postdoctoral fellowship. 2013- 2014.
-   Workshop coordinator: Graduate student coordinator for the U.C. Santa Cruz/Stanford Species Interactions Workshop. December 1, 2012.
-   Guest speaker: Jasper Ridge Biological Preserve summer intern and technician program. Camera traps, tracking and animal behavior, Stanford, CA. July 20, 2012
-   Panel Speaker: Portola Valley Conservation Committee, Balancing Fire Safety with Habitat Preservation, Portola Valley, CA. October 4, 2011
-   Biological Preserve Advisory Committee Member: Jasper Ridge Biological Preserve Advisory Committee, Stanford, CA. October 2009-2011
-   Treasurer/Founding Officer: Society for Conservation Biology, Central California Coast Chapter, Founding board member. October 2007-2010
-   Science Advisor: Mammals Focus Team, San Francisco Bay Area Upland Habitat Goals Project/Bay Area Open Space Council. Assisted in identifying and selecting conservation targets to represent mammalian biodiversity & critical habitat in the broader bay area. 2008-2010
-   Volunteer, Preparation Lab: Museum of Vertebrate Zoology, Berkeley, CA. Processed wildlife specimens; archival skeletal museum accessions. 2004-2007
-   Treasurer: Society for Conservation Biology, Berkeley Chapter, Berkeley, CA. Organized chapter activities and field trips, facilitated meetings, and managed fiscal matters. 2004-2005
-   Botanical Liaison: Native plant restoration project, Strawberry Creek, Berkeley, CA. Assisted in determining appropriate plants for specific ecological communities. 2004-2005

## Reports & Other Publications

Jonathan W. Long, Patricia N. Manley, Angela M. White, Keith M. Slauson, Stacy A. Drury, **Eric S. Abelson**, Brandon M. Collins, Keith Reynolds, William Elliot and I. Sue Miller, Rob Scheller, Charles Maxwell, Mariana Dobre, Erin Brooks, Sam Evans, Tim Holland, Matthew Potts, Adrian Harpold, Sebastian Krogh Navarro, John Mejia, Chad Hoffman, Justin Ziegler. Lake Tahoe West Science Summary of Findings Report. Supporting long-term forest resilience in the Lake Tahoe basin. Lake Tahoe West Restoration Partnership. (November 3, 2020)

## Selected Press

KTLA: As California eyes more wildlife crossings, researchers say some animals might be scared to use them. <https://tinyurl.com/bdnes4dy>. January 15, 2023

UCLA Newsroom: Is it safe? Why some animals fear using wildlife crossings. <https://tinyurl.com/4mh5pxxf>. December 22, 2022

Inside the Forest Service: Supporting long-term forest resilience in the Lake Tahoe basin. <https://www.fs.usda.gov/inside-fs/delivering-mission/sustain/supporting-long-term-forest-resilience-lake-tahoe-basin>. September 24, 2021

Lake Tahoe West Landscape Restoration Strategy. (<https://www.nationalforests.org/assets/images/LTW-Landscape-Restoration-Strategy-02Dec2019-FINAL.pdf>). December 2019

PSW Connections: Research project to help the science of wildlife passages along existing roadways. winter/spring/summer 2016 (<http://www.fs.fed.us/psw/>)

USFS The Chief’s Desk, People Places and Things: Science to guide California highway wildlife passages. July 20, 2016

Press coverage of Brain size is correlated with endangerment status in mammals published in the Proceedings of the Royal Society, Biology 2016: \> Interviews: Discovery Channel News, Ireland National Radio RTE Radio1, BBC Inside Science, Conservation Magazine, Stanford News Service \> Also reported by: Agence France Presse, BBC.com, RiAus, The Japan Times, Science Alert, Tech Times, Nature World News, Daily Mail, Phys.org, Laboratory Equipment

Quest TV, KQED: Cameras capture the secret lives of Jasper Ridge animals. September 25, 2012 (<http://science.kqed.org/quest/video/your-videos-on-quest-steve-fyffe>)

ABC 7, 6pm News: Life after dark in a bay area forest. August 3, 2012 (<http://abclocal.go.com/kgo/video?id=8761455&pid=null>)

Nature News & Scientific American: Mostly the big-brained survive. July 17, 2012 (<http://www.nature.com/news/mostly-the-big-brained-survive-1.11027> & <https://www.scientificamerican.com/article.cfm?id=mostly-big-brained-survive>)

Stanford News Service: Field research at Jasper Ridge, computers and cognition. (<http://news.stanford.edu/news/multi/features/jasper/part5.html>)

KZSU radio interview (Peninsula Report): Night life of local wildlife. June 8, 2012 (<http://kzsunews.tumblr.com/post/24714505458/elizaonair-this-week-we-talk-the-night-life-of>)

Stanford News Service, Video: Cameras capture biodiversity at Jasper Ridge preserve. June 1, 2012 (<http://youtu.be/CzSCu2FOj0Q>)

Stanford News Service: Caught on tape: The nightlife of animals at Stanford's Jasper Ridge preserve. May 31, 2012 (<http://news.stanford.edu/news/2012/june/jasper-ridge-cameras-060112.html>)

Stanford Report: Jasper Ridge, Research in the Field at Stanford’s Biological Preserve; Computers and Cognition. October 22, 2008 (also online at: <http://multi.stanford.edu/features/jasper/part5.html>)

## Grants & Honors

(\$622,695 since 2020)

-   Actions that Promote Community Transformation, Super Seed Grant: Access needs for STEM Students with Disabilities. Co-PI. (**\$14,000**). 2022-2023
-   Stengl-Wyer Grant: Integrating UT field stations into long-term, globally distributed ecological networks. Co-PI. (**\$147,792**). 2022-2025
-   Planet Texas 2050 (subaward): Automated sensor arrays to address long-term ecological shifts. (**\$27,100**). 2022-2023
-   Army Research Office (subaward): Science of embodied innovation, learning and control. (**\$27,496**). 2021-2023
-   Stengl-Wyer Grant: Leveraging big data science for ecological research in an era of global change: a Forest Global Earth Observatory (ForestGEO) plot at Stengl Lost Pines Biological Station. Co-PI. (**\$149,828**). 2021-2022
-   Stengl-Wyer Endowment: Integration of machine learning and remote sensing for improved understanding of environmental change in central Texas. Co-PI. (**\$256,479**). 2020-2023
-   USDA Forest Service: Exploring wildlife movements response to ephemeral vegetation dynamics – applying remote sensing to better understand wildlife movement at broad spatio-temporal scales. (**\$25,000**). 2019-2024.
-   UCLA La Kretz Center for California Conservation Science, Post-doctoral Fellowship. 2014-2015
-   Southern California Research Learning Center’s Grant Program, 2014-2016
-   National Science Foundation Dissertation Improvement Grant, 2011-2013
-   Woods Institute for the Environment, Stanford University, Rising Environmental Leader 2012
-   Stanford Ecology & Evolutionary Biology Travel Grant, 2012
-   #SciFund Challenge, 2011
-   Stanford SCORE Grant, 2009 & 2010
-   National Science Foundation Graduate Research Fellowship, Honorable Mention, 2008
-   Gomez Grant for Wildlife Ecology, 2007
-   U.C. Berkeley Grants and Honors:
    -   Highest honors in Conservation and Resource Studies, University of California, Berkeley. 2005
    -   Honors in the College of Natural Resources, University of California, Berkeley. 2005
    -   University Honors, University of California, Berkeley. 2003-2005
    -   Rosentiel Grant, 2005
    -   Student Life Advising Grant, University of California, Berkeley, 2005
    -   Undergraduate Research Opportunities Program Grant, College of Natural Resources, 2005
    -   Allmond Scholarship, 2003-2004
    -   Isais Hellman Scholarship, 2003-2004
    -   University of California at Berkeley University Grant 2003-2004
    -   Beth Blanchette Memorial Scholarship, 2003

## Ongoing Collaborative Projects

**Micro-to-Macro, UT Austin Energy Institute.** Investigating how and if microscale processes can be aggregated to consistently match macroscale patterns. <https://energy.utexas.edu/micro-macro>. 2021-present

**Resilient Species and Ecosystems, UT Austin Planet Texas 2050, Bridging Barriers.** <https://bridgingbarriers.utexas.edu/resilient-species-and-ecosystems>. 2022-present

## Teaching

-   Guest lecturer, UT Austin: Science literacy and numeracy: ecology and evolution. Wildlife behavior and decision making. November 2022
-   Guest lecturer, UT Austin Bio 398E: Subjects and skills for graduate students II. Wildlife ecology at the intersection of conservation and behavior. March 27, 2019
-   Guest Lecturer, Stanford Biology 105, Ecology and Natural History of Jasper Ridge Biological Preserve. Wildlife ecology and tracking. Stanford University, Stanford, CA. Winter 2009-2018
-   Guest Lecturer, UCSC Environmental Science 169, Global Change Ecology. Climate change and wildlife. University of California, Santa Cruz, Santa Cruz, CA. Winter 2014
-   Guest Lecturer, UCSC Environmental Science 104A. Introduction to Environmental Field Methods. Wildlife survey methods, monitoring and behavioral data collection. University of California, Santa Cruz, Santa Cruz, CA. Summer 2013
-   Teaching Assistant, Stanford Biology 312. Ethical Issues in Ecology and Evolutionary Biology. Stanford University, Stanford, CA. Autumn 2008
-   Teaching Assistant, Stanford Biology 145/245. Behavioral Ecology. Stanford University, Stanford, CA. Spring 2008

### Outreach Teaching

-   Panelist: Stanford Biology Career Panel. February 22, 2018.
-   Contributor: Educurious Non-profit K-12 curriculum developers: Camera trapping as a tool to understand wildlife behavior and ecology. April 10, 2012
-   Lecturer: Splash! Stanford Educational Studies Program for high school students: Why are some species endangered? Conservation Biology 101. Stanford University, Stanford, CA. April 2012
-   Mammal Identification Guide: Stanford BioBlitz, Stanford, CA. Led citizen science mammalian rapid biodiversity assessment. April 2011 & 2012
-   Volunteer instructor: Redwood High School Continuation Campus R.E.A.L. (Redwood Environmental Academy of Leadership), Redwood City, CA. Taught topics ranging from evolutionary biology to wildlife tracking. 2011
-   Lecturer/Volunteer, Splash! Stanford Educational Studies Program for high school students: Wildlife tracking: Stanford University, Stanford, CA. 2009, 2010, 2011
-   Presenter, Jordan Middle School Science Night: Hands-on demonstration of remote detection of wildlife using various camera-trap technologies. Jordan middle school, Palo Alto, CA. January 2010.
-   Volunteer, Plant Survey: Point Reyes Rare Plant-A-Thon, Point Reyes, CA. Assisted in documenting, mapping, and inventory of rare plant populations at the Point Reyes National Seashore. 2003
-   Volunteer, Tracking Survey: Peninsula Open Space Trust, Pescadero, CA. Worked with a team of trackers on a week-long wildlife presence or absence project 2001 ::: :::
